// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkzwxosinoitrslgkxwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrend4b3Npbm9pdHJzbGdreHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzgyNjksImV4cCI6MjA2MzMxNDI2OX0.AtB2nnQbpgIpYG0N54YlvqcbubhQMSe6Tkj1sbjxlK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);